# Generated by Django 5.0.3 on 2024-03-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wame_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email_verified',
        ),
    ]
